###**Unidad 4 - IMPORTANDO LIBRERIAS**

* **Numpy:** Importantes para estructuras de datos
* **Pandas:** Importante para manipulacion y analisis de datos
* **Random:** Para importar numeros aleatorio
* **Sys:** Para variables y funciones que interactuan directamente con Python
* **Matplotlib:** Permite hace graficos, Se va ver mas adelante

# Nueva sección

In [ ]:
# Importando bibliotecas
import numpy as np
import pandas as pd
import random as rd
import sys

#####**Trabajando con lista**

In [ ]:
# Creando una lista de 10 elementos
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
# Transformando una lista a array (arreglo de numpy)
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Promedio
promedio = np.mean(lista)
promedio

np.float64(5.5)

In [ ]:
# Consultando la cantidad de memoria ocupada por estructura
memoria_lista = sys.getsizeof(lista)
memoria_arreglo = arreglo.nbytes

print(f"Memoria ocupada por la lista: {memoria_lista} Bytes")
print(f"Memoria ocupada por el array: {memoria_arreglo} Bytes")

Memoria ocupada por la lista: 136 Bytes
Memoria ocupada por el array: 80 Bytes


####**Aplicando el paquete random**


In [ ]:
np.random.randint(1,100) # Generando numeros aleatorios del 1 al 100

50

In [ ]:
np.random.rand() # Genera numeros aleatorios del rango 0 a 1

0.5132387073593578

In [ ]:
np.random.rand(5) # Genera numeros aleatorios del rango de 0 a 1 pero con 5 elementos

array([0.49396933, 0.91488558, 0.70634343, 0.02862926, 0.53794952])

In [ ]:
np.random.randint(10) # Genera numeros aleatorios del rango de 0 a 1 con 10 elementos pero mas parecido a una matriz

9

In [ ]:
np.random.randint(1,100,10) # Del 1 al 100 me esta generando 10 numeros aleatorios

array([33, 24, 20, 63, 39, 58, 95, 73, 87, 29])

####**Imprimiendo numeros individuales en cierta cantidad**

In [ ]:
# Creando una lista de solo numeros UNOS
unos = np.ones(100)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Creando una lisa de solo numeros CEROS
ceros = np.zeros(100)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

####**Consultando el tipo de dato numerico del arreglo**

In [ ]:
arreglo.dtype

dtype('int64')

####**Lista de datos compuesto**

In [ ]:
lista2= ["Matias", True, 2, 5.6]
lista2

['Matias', True, 2, 5.6]

In [ ]:
arreglo2 = np.array(lista2)
arreglo2

array(['Matias', 'True', '2', '5.6'], dtype='<U32')

####**Otros metodos de numpy**

In [ ]:
print("Shape:", arreglo.shape) # Dimensiones
print("Dimensiones:", arreglo.ndim) # Numero de ejes
print("Tamaño:", arreglo.size) # Total de elementos
print("Tipo de dato:", arreglo.dtype) # Tipo almacenado
print("Bytes/elem:", arreglo.itemsize) # Tamaño en bytes de cada elemento

Shape: (10,)
Dimensiones: 1
Tamaño: 10
Tipo de dato: int64
Bytes/elem: 8


####**Transformando el arreglo de Int a Float**

In [ ]:
new_arreglo= arreglo.astype(np.float32) # Especificando que sea de 32 bits (ocupa menos memoria)
new_arreglo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

El metodo astype() transforma los elementos del arrelgo a un tipo determinado de dato numerico